apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}{{ .Values.db.service.name }}"
  labels:
    app: "{{ .Values.db.service.label }}"
spec:
  type: {{ .Values.db.service.type }}
  ports:  
  - port: {{ .Values.db.service.port.external | int }}
    targetPort: {{ .Values.db.container.port | int }}
    protocol: TCP
  selector:
    app: "{{ .Values.db.service.labelSelector }}"
